Spring web hw
IvanSvetov/web-library pull request #2
Opened 2023-05-24 04:38 UTC by IvanSvetov

2023-05-24 19:12 UTC, OlgaLugacheva requested changes

2023-05-24 19:12 UTC, OlgaLugacheva commented on src/main/java/skypro/java/course4/weblibrary/controller/EmployeeController.java
> + /*   @GetMapping
закомментированный код нужно убрать

2023-05-24 19:12 UTC, OlgaLugacheva commented on src/main/java/skypro/java/course4/weblibrary/model/Employee.java
> +/*    public Employee(String name, int salary) {
убрать

2023-05-24 19:12 UTC, OlgaLugacheva commented on src/main/java/skypro/java/course4/weblibrary/service/EmployeeServiceImpl.java
> +        return employees.get(id);
вероятно, эту строку нужно перенести на 23
и в противном случае бьросить исключение, например

2023-05-24 19:12 UTC, OlgaLugacheva commented on src/main/java/skypro/java/course4/weblibrary/service/EmployeeServiceImpl.java
> +
бросить исключение

2023-05-24 19:12 UTC, OlgaLugacheva commented on src/main/java/skypro/java/course4/weblibrary/service/EmployeeServiceImpl.java
> +
исключение

2023-05-24 19:12 UTC, OlgaLugacheva commented on src/main/java/skypro/java/course4/weblibrary/service/EmployeeServiceImpl.java
> +        return employees.get(id);
перенести на 49 строку
а вообще по смыслу такой метод уже есть

2023-05-24 19:12 UTC, OlgaLugacheva commented on src/main/java/skypro/java/course4/weblibrary/service/EmployeeServiceImpl.java
> +        return updated;
перенести на 57

2023-05-24 19:12 UTC, OlgaLugacheva commented on src/main/java/skypro/java/course4/weblibrary/service/EmployeeServiceImpl.java
> +        return null;
вернуть values для коллекции вместо null

2023-05-28 19:04 UTC, OlgaLugacheva requested changes

2023-05-28 19:04 UTC, OlgaLugacheva commented on src/main/java/skypro/java/course4/weblibrary/controller/EmployeeController.java
> +    public Employee deleteEmployee(@PathVariable Long id) {
тогда сделай метод void

2023-05-28 19:04 UTC, OlgaLugacheva commented on src/main/java/skypro/java/course4/weblibrary/controller/EmployeeController.java
> +        return null;
null убери

2023-05-28 19:04 UTC, OlgaLugacheva commented on src/main/java/skypro/java/course4/weblibrary/controller/EmployeeController.java
> +        return null;
этот метод, раз он тут есть, нужно реализовать

2023-05-28 19:04 UTC, OlgaLugacheva commented on src/main/java/skypro/java/course4/weblibrary/repository/EmployeeRepositoryImpl.java
> +        return null;
тут нужна реализация

2023-05-28 19:04 UTC, OlgaLugacheva commented on src/main/java/skypro/java/course4/weblibrary/service/EmployeeServiceImpl.java
> +        return employees.get(id);
тут не исправлено

2023-06-01 05:49 UTC, BizinMitya commented on src/main/java/skypro/java/course4/weblibrary/controller/EmployeeController.java
> +    ResponseEntity<Employee> ResponseEntity;
Это поле не нужно

2023-06-01 05:49 UTC, BizinMitya commented on src/main/java/skypro/java/course4/weblibrary/controller/EmployeeController.java
> +
здесь нужно вызвать метод сервиса для добавления сотрудника

2023-06-01 05:50 UTC, BizinMitya commented on src/main/java/skypro/java/course4/weblibrary/controller/EmployeeController.java
> +        Employee foundStudent = employeeService.edit(employee);
id не используется. Надо передавать вторым параметром в метод сервиса id и использовать его для поиска сотрудника

2023-06-01 05:50 UTC, BizinMitya commented on src/main/java/skypro/java/course4/weblibrary/controller/EmployeeController.java
> +        return ResponseEntity;
здесь надо вернуть обновленного сотрудника, если он был найден и 404 в противном случае, т.к. найден не был

2023-06-01 05:51 UTC, BizinMitya commented on src/main/java/skypro/java/course4/weblibrary/controller/EmployeeController.java
> +        return employeeService.find(id);
надо вернуть 404, если сотрудник не найден и найденного сотрудника, если был найден

2023-06-01 05:51 UTC, BizinMitya commented on src/main/java/skypro/java/course4/weblibrary/controller/EmployeeController.java
> +        return null;
надо вернуть 404, если сотрудник не был найден

2023-06-01 05:51 UTC, BizinMitya commented on src/main/java/skypro/java/course4/weblibrary/exceptions/EmployeeExceptionHandler.java
> +        return new ResponseEntity<>(HttpStatus.NOT_FOUND);
почему при IOException возвращается 404? надо создать своё исключение, которое надо кидать, когда сотрудник не будет найден и которое надо здесь обрабатывать

2023-06-01 05:52 UTC, BizinMitya commented on src/main/java/skypro/java/course4/weblibrary/exceptions/EmployeeExceptionHandler.java
> +public class EmployeeExceptionHandler extends RuntimeException {
почему класс расширяет RuntimeException ? этого не должно быть, класс должен быть сам по себе

2023-06-01 05:53 UTC, BizinMitya commented on src/main/java/skypro/java/course4/weblibrary/service/EmployeeServiceImpl.java
> +            throw new EmployeeExceptionHandler();
что это такое? здесь надо кидать своё созданное исключение, а не handler

2023-06-01 05:53 UTC, BizinMitya commented on src/main/java/skypro/java/course4/weblibrary/service/EmployeeServiceImpl.java
> +            throw new EmployeeExceptionHandler();
что это такое? здесь надо кидать своё созданное исключение, а не handler

2023-06-01 05:53 UTC, BizinMitya commented on src/main/java/skypro/java/course4/weblibrary/service/EmployeeServiceImpl.java
> +        }
здесь надо кидать своё созданное исключение, а не handler

2023-06-01 05:53 UTC, BizinMitya commented on src/main/java/skypro/java/course4/weblibrary/service/EmployeeServiceImpl.java
> +            throw new EmployeeExceptionHandler();
что это такое? здесь надо кидать своё созданное исключение, а не handler

2023-06-01 05:53 UTC, BizinMitya commented on src/main/java/skypro/java/course4/weblibrary/service/EmployeeServiceImpl.java
> +        return (Collection<Employee>) employees;
здесь ошибка, как ты кастишь мапу к коллекции? это неверно и будет исключение

2023-06-09 05:21 UTC, merged